name: build

on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.11
      - name: setup build environment
        run: docker build -t build_env .
      - name: build
        run: docker run -v "$PWD":/data build_env make
      - uses: actions/upload-artifact@v2
        with:
          name: thesis
          path: build/thesis.pdf

  release:
    name: release
    runs-on: ubuntu-latest
    needs: build

    if: startsWith(github.event.ref, 'refs/tags/v')

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: thesis

      - uses: "marvinpinto/action-automatic-releases@v1.2.0"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: thesis.pdf
